### ISSUE TITLE
Dublin Core attributes or elements?

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/schemas#24]
Original comment for @1313ou

>The dc: attributes are defined as elements not attributes by Dublin Core so that any attempt to validate against this external reference will fail. How to see this ?
> The namespace URL http://purl.org/dc/elements/1.1/ redirects to
> http://dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/?v=elements
>
> This page maps the URL to a schema location and contains the following:
>
> Target namespace: http://purl.org/dc/elements/1.1/
> Schema location: http://dublincore.org/schemas/xmls/qdc/2008/02/11/dc.xsd

The proposed change would be to change the DC attributes to elements. The obvious issue with this is that it breaks backwards compatibility, and the guidelines on Dublin Core are not a hard requirement (RDF for example uses attributes).

**Comment by goodmami** [comment]
In #5 I said:

> The DC metadata don't follow the actual Dublin Core schema, so using the `dc:` namespace seems a little problematic.

By this I meant that perhaps we should just not use `dc:` but keep them as attributes. This is because the `dc` namespace links to a schema that doesn't actually describe the structure of our metadata, although in a general sense we are using the attributes for the same purpose as the DC elements. In other words, the intent is compatible, but the technical solution is not, and I don't like the idea of using "heavy" elements just to resolve the technical issue. Furthermore, if #25 and #26 result in this metadata changing shape somehow, then there remains only one "DC-like" attribute in use in the EWN, and we may find the overall metadata scheme less compelling. Unfortunately I don't know to what extent non-EWN projects use the DC-like attributes.

We could also just publish an alternative, DC-derived metadata schema (licensed and with attribution to the original as appropriate) that describes the metadata as attributes. Then we'd only need to update the URL in our wordnets.

**Comment by fcbond** [comment]
I like Michael's proposal of just dropping the dc (and adding in the documentation that they are inspired by the Dublin core).

**Comment by jmccrae** [comment]
I could live with dropping the namespace... although this would still affect backwards compatibility.

**Comment by 1313ou** [comment]
The point I am making is 
-having a dc: name space is not a problem per se, dc could mean 'document core'  
-the problem is the reference to "http://purl.org/dc/elements/1.1/" which is registered externally and has a location and definition attached to it.
-you could have a different URL (for instance http://gwa.org/schemas/dc/) that defines it correctly.

**Comment by jmccrae** [comment]
Okay, so I suggest we just change the prefix `dc` to `https://globalwordnet.github.io/schemas/dc` e.g.,

```xml
<LexicalResource xmlns:dc="https://globalwordnet.github.io/schemas/dc">
```

I am not quite sure what (if anything) we should put at this URL.

**Comment by goodmami** [comment]
Sounds great

> I am not quite sure what (if anything) we should put at this URL.

How about a basic HTML page with something like:

> ##### WordNet Metadata Attributes
>
> The Global WordNet Association allows metadata attributes to be embedded within a wordnet document. The following fourteen  attributes are inspired by the [Dublin Core](http://purl.org/dc/elements/1.1/) Metadata Element Set and have the same usage, and for this reason they may appear with a `dc` namespace linked to this document.
>
> * [dc:contributor](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/elements/1.1/contributor)
> * [dc:coverage](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/elements/1.1/coverage)
> * [...]
>
> ##### Historical Note
>
> Previously the `dc` namespace linked directly to Dublin Core, but it was changed because the WordNet Metadata Attributes do not use the Dublin Core elements as specified, but only its conceptual framework.

Or something to that effect. I don't think it should be a big document, but if someone navigates to the URL they should get *some* description of the attributes.

**Comment by 1313ou** [comment]
It is good practise for the page (or accessible pages) to have a reference to a Schema Location: see https://www.dublincore.org/schemas/xmls/
